### ISSUE TITLE
Not Working on another computer

### ISSUE THREAD

**Issue by jmmccarthy2002** [Funbit/ets2-telemetry-server#45] opened 2015-03-19 02:03 UTC
Hi!

I installed the server and it works fine on the PC that the server and ETS2 are running on, but when I try to connect to it on my laptop, it says the webpage is unavailable, even though they are both on the same wifi network. Do you know how to fix this?

Thanks!

**Comment by jmmccarthy2002** [comment] 2015-03-19 02:24
I have also done what your faq said to do

**Comment by Funbit** [comment] 2015-03-19 02:38
I'm sorry, but I have to recommend you to read the FAQ and last 15 pages of the official thread on SCS forum (see Links section).
The problem usually lies in the firewall settings (if you have third party firewall/antivirus) or network settings.

**Comment by Funbit** [comment] 2015-03-22 03:01
@jmmccarthy2002 
Any progress?

**Comment by jmmccarthy2002** [comment] 2015-03-22 14:36
Not at the moment. I also tried turning my anti virus off and using my phone instead of my laptop to display the html5. The funny thing is it works perfectly on the same computer the server exe is on

**Comment by yodek** [comment] 2015-03-22 17:18
Looks like problems with connection between computer and other device [laptop] - like firewall / antivirus BLOCK port 25555 ? Did you add manually ACL rule ?

I'm not suprise that starting webpage on computer where is Telemetry-server works.

I checked on my laptop and Raspberry Pi - works.

**Comment by Funbit** [comment] 2015-03-28 05:57
@jmmccarthy2002 
I'm sorry, but I have to close this issue because it is not reproducable and related to the particular environment.

**Closed by Funbit** 2015-03-28 05:57 UTC
